## 2.4.1 넘파이

### 넘파이 배열

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3], [1,5,9], [3,5,7]])

print(a.ndim)  
# 2 

print(a.shape) 
# (3,3)


print(a.size) 
# 9


print(a.dtype) 
# dtype('int32')

In [ ]:
a = np.zeros((2,3)) #원소가 모두 0인 배열 생성
print(a)      
# array([[0., 0., 0.],
#        [0., 0., 0.]])

b = np.ones((2,1)) #원소가 모두 1인 배열 생성
print(b)      
# array([[1.],
#        [1.]])

c = np.empty((2,2)) #원소값을 초기화하지 않은 배열 생성
print(c)      
# array([[1.96088859e+243, 5.22864540e-067],
#        [1.47173270e-052, 1.47214053e-052]])


d = np.arange(10, 30, 5) # 10부터 30전 까지 5단위로 배열 생성
print(d)      
# array([10, 15, 20, 25])


e = np.full((2, 2), 4) #원소가 모두 4인 배열 생성
print(e)      
# array([[4, 4],
#        [4, 4]])


f = np.eye(3) # 3x3 크기의 단위행렬 생성
print(f)      
# array([[1., 0., 0.],
#        [0., 1., 0.]
#        [0., 0., 1.]))


g = np.random.random((2, 2)) # 임의값을 가지는 배열 생성
print(g)      
# array([[0.94039485, 0.18284953],
#        [0.59283818, 0.48592838]])

### 넘파이 기본연산

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a+b)                     
# array([11, 22, 33])

print(np.add(a,b)) # 위의 연산과 같다.        
# array([11, 22, 33]) 

print(b-a)                      
# array([9, 18, 27])

print(np.subtract(b,a)) # 위의 연산과 같다.
# array([9, 18, 27])

print(a**2)                   
# array([1, 4, 9])


print(b<15)                   
# array([True, False, False])


C = np.array([[1, 2],
              [3, 4]])
D = np.array([[10, 20],
              [30, 10]])
print(C*D)  # 원소별 곱셈
# array([[10, 40],
#        [90, 40]])


print(np.dot(C,D)) # 내적(dot product) 계산
# array([[ 70,  40],
#        [150, 100]])


print(C.dot(D)) #내적의 또 다른 사용법
# array([[ 70,  40],
#        [150, 100]])

In [ ]:
a = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 1, 3, 5, 7]])

print(a.sum(axis=0)) # 0축, 즉 열을 기준으로한 덧셈
# array([7, 11, 15, 19])

print(a.sum(axis=1)) # 1축, 즉 행을 기준으로한 덧셈
# array([10, 26, 16])


print(a.max(axis=1)) # 각 행에서의 최대값
# array([4, 8, 7])

### 넘파이 배열 인덱싱, 슬라이싱

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[3]) 
# 4


print(a[-1]) # 마지막 원소
# 7


print(a[2: 5]) # 인덱스값 5를 가지는 원소 전까지
# array([3, 4, 5])


print(a[2: ])
# array([3, 4, 5, 6, 7])


print(a[ :4])
# array([1, 2, 3, 4])

In [ ]:
a = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]])


print(a[1, 2])
# 6


print(a[ : , 1]) # 1열의 모든 원소
# array([2, 5, 8])


print(a[-1]) # 마지막 행
# array([7, 8, 9])

### 넘파이 배열 형태 변환

In [ ]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

print(a.ravel()) # 1차원 배열(벡터)로 만들어준다.
# array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(a.reshape(2, 6))
# array([[  1,  2,  3,  4,  5,  6],
#        [  7,  8,  9, 10, 11, 12]])


print(a.T)
# array([[  1,  5,  9],
#        [  2,  6, 10],
#        [  3,  7, 11],
#        [  4,  8, 12]])

In [ ]:
print(a.reshape(3, -1)) # 3행만 지정해주고 열에 -1을 넣으면 자동으로 배열을 reshape한다.
# array([[  1,  2,  3,  4],
#        [  5,  6,  7,  8],
#        [  9, 10, 11, 12]]) 

### 넘파이 브로드캐스팅

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])
y = np.empty_like(a) # 배열 a와 크기가 같은 원소가 비어있는 배열 생성

# 배열 b를 a의 각 행에 더해주기 위해 반복문을 사용한다.
for i in range(3):
    y[i, : ] = a[i, : ] + b


print(y)
# array([[  2,  2,  4],
#        [  5,  5,  7],
#        [  8,  8, 10]])

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])

c = a + b # c를 따로 선언 할 필요 없이 만들 수 있다.
print(c)
# array([[  2,  2,  4],
#        [  5,  5,  7],
#        [  8,  8, 10]])